# Generated by Django 3.2.25 on 2024-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/du2uzk3no/image/upload/v1714042156/default_profile_nwigev.jpg', upload_to='images/'),
        ),
    ]
