# Generated by Django 3.2.25 on 2024-07-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/du2uzk3no/image/upload/v1714042156/default_profile_nwigev.jpg', upload_to='media/'),
        ),
    ]
