# Generated by Django 3.2.25 on 2024-07-10 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_members_team_users'),
        ('tasks', '0011_alter_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_profiles',
        ),
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='teams.team'),
        ),
    ]
